Complete product tests for coverage and Add stryker config for mutation testing
FynnSchapdick/HouseholdManager pull request #8
Opened 2023-06-12 18:59 UTC by FynnSchapdick

2023-06-12 19:01 UTC, devfinnd requested changes

2023-06-12 19:01 UTC, devfinnd commented on Tests/ShoppingService.UnitTests/Test_ShoppingList_AddItem.cs
> +            .Which.Should().BeForShoppingListId(shoppingList.Id)
because string fehlt

2023-06-12 19:01 UTC, devfinnd commented on Tests/ShoppingService.UnitTests/Test_ShoppingList_Create.cs
> +            .Which.Should().NotHaveDefaultId()
because string

2023-06-12 19:01 UTC, devfinnd commented on Tests/ShoppingService.UnitTests/Test_ShoppingList_Create.cs
> +            .And.BeEmpty();
because string

2023-06-13 07:48 UTC, devfinnd requested changes
Ich dachte logging kannst du...

2023-06-13 08:40 UTC, FynnSchapdick commented on Tests/ProductService.UnitTests/Test_Product_Create.cs
> +            .And.HaveName(name, $"because product was instantiated with name {name}");
Oh ja upsi

2023-06-13 08:45 UTC, devfinnd approved these changes
👍

2023-06-13 09:13 UTC, merged